spring:
  profiles:
    active:
      - dev

---
# 配置服务器信息
server:
  port: 8001

# 数据库信息配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: password
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接的最大超时时间

# Mybatis配置
mybatis:
  mapper-locations:                                       # mapper映射文件所在路径
    - classpath:/mybatis/mapper/**/*.xml
  type-aliases-package: com.rain.springcloud.entity       # Entity别名类所在包路径
  config-location: classpath:/mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径

# Eureka配置
eureka:
  client:                                       # Eureka客户端注册进Eureka服务端的服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka    # 单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:                                     # 定制注册进Eureka服务的名称
    instance-id: springcloud-config-dept-provider-client-8001
    prefer-ip-address: true                     # 访问路径可以显示IP地址

# 服务info配置
info:
  app.name: rain-springcloud
  company.name: www.rainsun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
# 配置服务器信息
server:
  port: 8001

# 数据库信息配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud02
    username: root
    password: password
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接的最大超时时间

# Mybatis配置
mybatis:
  mapper-locations:                                       # mapper映射文件所在路径
    - classpath:/mybatis/mapper/**/*.xml
  type-aliases-package: com.rain.springcloud.entity       # Entity别名类所在包路径
  config-location: classpath:/mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径

# Eureka配置
eureka:
  client:                                       # Eureka客户端注册进Eureka服务端的服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka    # 单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:                                     # 定制注册进Eureka服务的名称
    instance-id: springcloud-config-dept-provider-client-8001
    prefer-ip-address: true                     # 访问路径可以显示IP地址

# 服务info配置
info:
  app.name: rain-springcloud
  company.name: www.rainsun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
